2024-04-14T23:36:29 {"cpu": 0.81884765625, "cpu_total": 4, "cpu_usage": 0.2047119140625, "memory": 5121.0, "memory_total": 8874.0, "memory_usage": 0.577079107505071, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137789.465322, "uuid": "bf60748485f741eaa665c78377831a81"}
2024-04-14T23:36:51 {"cpu": 0.93017578125, "cpu_total": 4, "cpu_usage": 0.2325439453125, "memory": 5585.0, "memory_total": 8874.0, "memory_usage": 0.6293666892044174, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137811.583474, "uuid": "927c690d6d934a779d71a611a4c580cc"}
2024-04-14T23:37:05 {"cpu": 0.99072265625, "cpu_total": 4, "cpu_usage": 0.2476806640625, "memory": 5526.0, "memory_total": 8874.0, "memory_usage": 0.6227180527383367, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137825.463858, "uuid": "a09cca1a9ab649a2b8bf5c00c1ae5c6b"}
2024-04-14T23:37:17 {"cpu": 1.017578125, "cpu_total": 4, "cpu_usage": 0.25439453125, "memory": 5131.0, "memory_total": 8874.0, "memory_usage": 0.5782059950416948, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137837.147931, "uuid": "abfabc5daa4f494bbf124913126e23d6"}
2024-04-14T23:37:28 {"cpu": 1.0498046875, "cpu_total": 4, "cpu_usage": 0.262451171875, "memory": 5564.0, "memory_total": 8874.0, "memory_usage": 0.6270002253775073, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137848.216894, "uuid": "28541e3c25234fe9b585a47442eeb2f4"}
2024-04-14T23:37:39 {"cpu": 1.08740234375, "cpu_total": 4, "cpu_usage": 0.2718505859375, "memory": 5241.0, "memory_total": 8874.0, "memory_usage": 0.5906017579445572, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137859.288273, "uuid": "58f388b7b42947b99b7b4ba4f5c25636"}
2024-04-14T23:37:48 {"cpu": 1.09765625, "cpu_total": 4, "cpu_usage": 0.2744140625, "memory": 5421.0, "memory_total": 8874.0, "memory_usage": 0.6108857336037864, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137868.036022, "uuid": "f5f8384475894e4c91b484a861f18489"}
2024-04-14T23:37:54 {"block_run_id": 216, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Execute PipelineRun 108, BlockRun 216: pipeline fantastic_spellcaster block dwn_ticker_price", "timestamp": 1713137874.379846, "uuid": "fcb27bc4122e4b62bde63a718f7d4b11"}
2024-04-14T23:37:56 {"cpu": 1.11328125, "cpu_total": 4, "cpu_usage": 0.2783203125, "memory": 5411.0, "memory_total": 8874.0, "memory_usage": 0.6097588460671625, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137876.827407, "uuid": "cc3b1df06dfb4c7bb0cf4e2376a19c3c"}
2024-04-14T23:38:04 {"cpu": 1.10595703125, "cpu_total": 4, "cpu_usage": 0.2764892578125, "memory": 5298.0, "memory_total": 8874.0, "memory_usage": 0.597025016903313, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137884.698801, "uuid": "28ba34367fb24281938d13605e7e2964"}
2024-04-14T23:38:05 {"block_run_id": 216, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "EXCEPTION", "message": "BlockRun 216 (block_uuid: dwn_ticker_price) failed.", "timestamp": 1713137885.863789, "uuid": "ca1a59b60c8543ca82e4f520cda11a8a", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1665, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1704, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 32, in load_data\n  File \"/home/src/./src/data_ingestion/download_ticker_data.py\", line 64, in download_ticker_data\n    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)\n  File \"/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py\", line 894, in download_symbol\n    df = client.get_bars(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 735, in get_bars\n    bars = list(self.get_bars_iter(symbol,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 718, in get_bars_iter\n    for bar in bars:\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 594, in _data_get\n    resp = self.data_get(path, data=data, feed=feed,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 274, in data_get\n    return self._request(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 222, in _request\n    return self._one_request(method, url, opts, retry)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 248, in _one_request\n    raise_api_error(resp, http_error)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 83, in raise_api_error\n    raise APIError(error, http_error) from None\nalpaca_trade_api.rest.APIError: too many requests.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1552, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 182, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["too many requests."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1665, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1704, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 32, in load_data
  File "/home/src/./src/data_ingestion/download_ticker_data.py", line 64, in download_ticker_data
    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)
  File "/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py", line 894, in download_symbol
    df = client.get_bars(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 735, in get_bars
    bars = list(self.get_bars_iter(symbol,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 718, in get_bars_iter
    for bar in bars:
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 594, in _data_get
    resp = self.data_get(path, data=data, feed=feed,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 274, in data_get
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 222, in _request
    return self._one_request(method, url, opts, retry)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 248, in _one_request
    raise_api_error(resp, http_error)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 83, in raise_api_error
    raise APIError(error, http_error) from None
alpaca_trade_api.rest.APIError: too many requests.
2024-04-14T23:38:14 {"cpu": 1.10986328125, "cpu_total": 4, "cpu_usage": 0.2774658203125, "memory": 5395.0, "memory_total": 8874.0, "memory_usage": 0.6079558260085643, "pipeline_run_id": 108, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 108 in schedule 1 is alive.", "timestamp": 1713137894.735594, "uuid": "26fac3f8c5f6437082d82c769f11c030"}
