2024-04-14T23:36:24 {"cpu": 0.763671875, "cpu_total": 4, "cpu_usage": 0.19091796875, "memory": 4789.0, "memory_total": 8874.0, "memory_usage": 0.5396664412891593, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137784.492595, "uuid": "c868bffe10bb4153a87e9a45118f6c72"}
2024-04-14T23:36:50 {"cpu": 0.93017578125, "cpu_total": 4, "cpu_usage": 0.2325439453125, "memory": 5551.0, "memory_total": 8874.0, "memory_usage": 0.6255352715798963, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137810.620744, "uuid": "7fda6f70c4bf4242a09b5cd857fead16"}
2024-04-14T23:37:04 {"cpu": 0.99072265625, "cpu_total": 4, "cpu_usage": 0.2476806640625, "memory": 5356.0, "memory_total": 8874.0, "memory_usage": 0.6035609646157314, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137824.386443, "uuid": "26a838f7fd0d43f0bce84ee8b4fe39d6"}
2024-04-14T23:37:15 {"cpu": 1.01806640625, "cpu_total": 4, "cpu_usage": 0.2545166015625, "memory": 5543.0, "memory_total": 8874.0, "memory_usage": 0.6246337615505972, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137835.787547, "uuid": "5ce8db10ce2e4841a70db0ab431d3151"}
2024-04-14T23:37:27 {"cpu": 1.0498046875, "cpu_total": 4, "cpu_usage": 0.262451171875, "memory": 5300.0, "memory_total": 8874.0, "memory_usage": 0.5972503944106378, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137847.124472, "uuid": "7a27d8a708c2493287775452e620267f"}
2024-04-14T23:37:37 {"cpu": 1.08740234375, "cpu_total": 4, "cpu_usage": 0.2718505859375, "memory": 4862.0, "memory_total": 8874.0, "memory_usage": 0.5478927203065134, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137857.453359, "uuid": "cc782115071643ba981d3bb7de39e3ce"}
2024-04-14T23:37:41 {"block_run_id": 190, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Execute PipelineRun 95, BlockRun 190: pipeline fantastic_spellcaster block dwn_ticker_price", "timestamp": 1713137861.224933, "uuid": "0b78f51f585a45688cb80ef7be8ef5d7"}
2024-04-14T23:37:47 {"cpu": 1.09765625, "cpu_total": 4, "cpu_usage": 0.2744140625, "memory": 5592.0, "memory_total": 8874.0, "memory_usage": 0.6301555104800541, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137867.009455, "uuid": "4a735f4912ed459fb338fcc8bc8e8b12"}
2024-04-14T23:37:55 {"cpu": 1.11328125, "cpu_total": 4, "cpu_usage": 0.2783203125, "memory": 5541.0, "memory_total": 8874.0, "memory_usage": 0.6244083840432725, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137875.7483, "uuid": "5d316c74f71b48dc9e055c0431e870e6"}
2024-04-14T23:38:03 {"cpu": 1.10595703125, "cpu_total": 4, "cpu_usage": 0.2764892578125, "memory": 5351.0, "memory_total": 8874.0, "memory_usage": 0.6029975208474194, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137883.02325, "uuid": "73327f4f363243e8878595ecf6005c42"}
2024-04-14T23:38:11 {"block_run_id": 190, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "EXCEPTION", "message": "BlockRun 190 (block_uuid: dwn_ticker_price) failed.", "timestamp": 1713137891.275618, "uuid": "3dfdcc3841c3498bb11cc751f4443ff1", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1665, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1704, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 32, in load_data\n  File \"/home/src/./src/data_ingestion/download_ticker_data.py\", line 64, in download_ticker_data\n    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)\n  File \"/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py\", line 894, in download_symbol\n    df = client.get_bars(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 735, in get_bars\n    bars = list(self.get_bars_iter(symbol,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 718, in get_bars_iter\n    for bar in bars:\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 594, in _data_get\n    resp = self.data_get(path, data=data, feed=feed,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 274, in data_get\n    return self._request(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 222, in _request\n    return self._one_request(method, url, opts, retry)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 248, in _one_request\n    raise_api_error(resp, http_error)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 83, in raise_api_error\n    raise APIError(error, http_error) from None\nalpaca_trade_api.rest.APIError: too many requests.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1552, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 182, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["too many requests."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1665, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1704, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 32, in load_data
  File "/home/src/./src/data_ingestion/download_ticker_data.py", line 64, in download_ticker_data
    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)
  File "/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py", line 894, in download_symbol
    df = client.get_bars(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 735, in get_bars
    bars = list(self.get_bars_iter(symbol,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 718, in get_bars_iter
    for bar in bars:
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 594, in _data_get
    resp = self.data_get(path, data=data, feed=feed,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 274, in data_get
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 222, in _request
    return self._one_request(method, url, opts, retry)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 248, in _one_request
    raise_api_error(resp, http_error)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 83, in raise_api_error
    raise APIError(error, http_error) from None
alpaca_trade_api.rest.APIError: too many requests.
2024-04-14T23:38:13 {"cpu": 1.10986328125, "cpu_total": 4, "cpu_usage": 0.2774658203125, "memory": 5386.0, "memory_total": 8874.0, "memory_usage": 0.6069416272256029, "pipeline_run_id": 95, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 95 in schedule 1 is alive.", "timestamp": 1713137893.563672, "uuid": "68ce131165c549ecbcd0c1f5062d3236"}
