2024-04-14T23:36:33 {"cpu": 0.87890625, "cpu_total": 4, "cpu_usage": 0.2197265625, "memory": 5564.0, "memory_total": 8874.0, "memory_usage": 0.6270002253775073, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137793.009869, "uuid": "2ef1166a76904c4dbeedccf224738c1a"}
2024-04-14T23:36:52 {"cpu": 0.9736328125, "cpu_total": 4, "cpu_usage": 0.243408203125, "memory": 5093.0, "memory_total": 8874.0, "memory_usage": 0.5739238224025243, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137812.637733, "uuid": "43807a1174d14facb36382a98258ba79"}
2024-04-14T23:37:06 {"cpu": 0.99072265625, "cpu_total": 4, "cpu_usage": 0.2476806640625, "memory": 5401.0, "memory_total": 8874.0, "memory_usage": 0.6086319585305386, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137826.358649, "uuid": "cc34909f4fa549eba0710904cb0603ca"}
2024-04-14T23:37:18 {"cpu": 1.017578125, "cpu_total": 4, "cpu_usage": 0.25439453125, "memory": 5432.0, "memory_total": 8874.0, "memory_usage": 0.6121253098940725, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137838.216066, "uuid": "59d29af79a9c4525b70ee44a74613fdf"}
2024-04-14T23:37:29 {"cpu": 1.0498046875, "cpu_total": 4, "cpu_usage": 0.262451171875, "memory": 5329.0, "memory_total": 8874.0, "memory_usage": 0.600518368266847, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137849.579427, "uuid": "980b08745d964655b48d95db664614bc"}
2024-04-14T23:37:40 {"cpu": 1.08740234375, "cpu_total": 4, "cpu_usage": 0.2718505859375, "memory": 5572.0, "memory_total": 8874.0, "memory_usage": 0.6279017354068064, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137860.704207, "uuid": "0b4831240e674fc1b9e5f2f050a75710"}
2024-04-14T23:37:48 {"cpu": 1.09765625, "cpu_total": 4, "cpu_usage": 0.2744140625, "memory": 5174.0, "memory_total": 8874.0, "memory_usage": 0.5830516114491774, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137868.98969, "uuid": "bcbb27890bc0466f84327fbfffa5c1f1"}
2024-04-14T23:37:57 {"cpu": 1.1123046875, "cpu_total": 4, "cpu_usage": 0.278076171875, "memory": 5501.0, "memory_total": 8874.0, "memory_usage": 0.6199008338967771, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137877.732236, "uuid": "bc2c62b4799b4bc4a8375e4745626b62"}
2024-04-14T23:38:05 {"cpu": 1.10595703125, "cpu_total": 4, "cpu_usage": 0.2764892578125, "memory": 5562.0, "memory_total": 8874.0, "memory_usage": 0.6267748478701826, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137885.829369, "uuid": "34c51e13a29244ec8f2533621856c3e3"}
2024-04-14T23:38:10 {"block_run_id": 238, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Execute PipelineRun 119, BlockRun 238: pipeline fantastic_spellcaster block dwn_ticker_price", "timestamp": 1713137890.464652, "uuid": "ed8c62aad8ca464bb87fb2f51684856a"}
2024-04-14T23:38:16 {"cpu": 1.10986328125, "cpu_total": 4, "cpu_usage": 0.2774658203125, "memory": 5012.0, "memory_total": 8874.0, "memory_usage": 0.564796033355871, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137896.264359, "uuid": "4cf8bbc758264bd3a497a639ab0157c4"}
2024-04-14T23:38:24 {"block_run_id": 238, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "EXCEPTION", "message": "BlockRun 238 (block_uuid: dwn_ticker_price) failed.", "timestamp": 1713137904.168658, "uuid": "8952a47c7cdf491ca31dc174d0ff24c4", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1665, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1704, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 32, in load_data\n  File \"/home/src/./src/data_ingestion/download_ticker_data.py\", line 64, in download_ticker_data\n    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)\n  File \"/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py\", line 894, in download_symbol\n    df = client.get_bars(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 735, in get_bars\n    bars = list(self.get_bars_iter(symbol,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 718, in get_bars_iter\n    for bar in bars:\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 594, in _data_get\n    resp = self.data_get(path, data=data, feed=feed,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 274, in data_get\n    return self._request(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 222, in _request\n    return self._one_request(method, url, opts, retry)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 248, in _one_request\n    raise_api_error(resp, http_error)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 83, in raise_api_error\n    raise APIError(error, http_error) from None\nalpaca_trade_api.rest.APIError: too many requests.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1552, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 182, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["too many requests."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1665, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1704, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 32, in load_data
  File "/home/src/./src/data_ingestion/download_ticker_data.py", line 64, in download_ticker_data
    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)
  File "/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py", line 894, in download_symbol
    df = client.get_bars(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 735, in get_bars
    bars = list(self.get_bars_iter(symbol,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 718, in get_bars_iter
    for bar in bars:
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 594, in _data_get
    resp = self.data_get(path, data=data, feed=feed,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 274, in data_get
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 222, in _request
    return self._one_request(method, url, opts, retry)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 248, in _one_request
    raise_api_error(resp, http_error)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 83, in raise_api_error
    raise APIError(error, http_error) from None
alpaca_trade_api.rest.APIError: too many requests.
2024-04-14T23:38:24 {"cpu": 1.12451171875, "cpu_total": 4, "cpu_usage": 0.2811279296875, "memory": 5487.0, "memory_total": 8874.0, "memory_usage": 0.6183231913455037, "pipeline_run_id": 119, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 119 in schedule 1 is alive.", "timestamp": 1713137904.822277, "uuid": "ed779b2e347a49dfab268a0daba82f52"}
