2024-04-14T23:36:30 {"cpu": 0.81884765625, "cpu_total": 4, "cpu_usage": 0.2047119140625, "memory": 5257.0, "memory_total": 8874.0, "memory_usage": 0.5924047780031553, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137790.141502, "uuid": "04d4fac6c1664956bcf7d8ac8133e0e3"}
2024-04-14T23:36:51 {"cpu": 0.93017578125, "cpu_total": 4, "cpu_usage": 0.2325439453125, "memory": 5405.0, "memory_total": 8874.0, "memory_usage": 0.6090827135451882, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137811.816612, "uuid": "137fecf8af9e4f3ca8e1b77f7d93da92"}
2024-04-14T23:37:05 {"cpu": 0.99072265625, "cpu_total": 4, "cpu_usage": 0.2476806640625, "memory": 5531.0, "memory_total": 8874.0, "memory_usage": 0.6232814965066487, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137825.612289, "uuid": "28d591a16bc9413ebac197baa09e22b6"}
2024-04-14T23:37:17 {"cpu": 1.017578125, "cpu_total": 4, "cpu_usage": 0.25439453125, "memory": 5234.0, "memory_total": 8874.0, "memory_usage": 0.5898129366689204, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137837.365132, "uuid": "9870ec0ed52846ee85fa6a63b7b56f7d"}
2024-04-14T23:37:28 {"cpu": 1.0498046875, "cpu_total": 4, "cpu_usage": 0.262451171875, "memory": 5587.0, "memory_total": 8874.0, "memory_usage": 0.6295920667117422, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137848.428669, "uuid": "57988814ec0a42e7884a5c8a2dd3f937"}
2024-04-14T23:37:39 {"cpu": 1.08740234375, "cpu_total": 4, "cpu_usage": 0.2718505859375, "memory": 5342.0, "memory_total": 8874.0, "memory_usage": 0.6019833220644579, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137859.551239, "uuid": "7231303e8a2746cea59f0af0897ee735"}
2024-04-14T23:37:48 {"cpu": 1.09765625, "cpu_total": 4, "cpu_usage": 0.2744140625, "memory": 5064.0, "memory_total": 8874.0, "memory_usage": 0.5706558485463151, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137868.258188, "uuid": "a1ea0b1f40a04c84858f89531701ff15"}
2024-04-14T23:37:56 {"cpu": 1.1123046875, "cpu_total": 4, "cpu_usage": 0.278076171875, "memory": 5412.0, "memory_total": 8874.0, "memory_usage": 0.6098715348208249, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137876.96914, "uuid": "55af6273f746442bbf4a9bc3674e07b2"}
2024-04-14T23:37:57 {"block_run_id": 220, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Execute PipelineRun 110, BlockRun 220: pipeline fantastic_spellcaster block dwn_ticker_price", "timestamp": 1713137877.3779, "uuid": "6a29e31592594706a72333de5776b482"}
2024-04-14T23:38:04 {"cpu": 1.10595703125, "cpu_total": 4, "cpu_usage": 0.2764892578125, "memory": 5415.0, "memory_total": 8874.0, "memory_usage": 0.610209601081812, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137884.915207, "uuid": "398abd8cad9141bdbad1caf14eb52d4e"}
2024-04-14T23:38:15 {"cpu": 1.10986328125, "cpu_total": 4, "cpu_usage": 0.2774658203125, "memory": 5412.0, "memory_total": 8874.0, "memory_usage": 0.6098715348208249, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137895.007571, "uuid": "05c5320170474c2eb8edd31a92d96294"}
2024-04-14T23:38:23 {"cpu": 1.12451171875, "cpu_total": 4, "cpu_usage": 0.2811279296875, "memory": 5538.0, "memory_total": 8874.0, "memory_usage": 0.6240703177822853, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137903.800999, "uuid": "1c19b4c350bf44489cf0574bc1fbc014"}
2024-04-14T23:38:30 {"block_run_id": 220, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "EXCEPTION", "message": "BlockRun 220 (block_uuid: dwn_ticker_price) failed.", "timestamp": 1713137910.916433, "uuid": "5f3e0bd50df14eb2855581e5f1db0ea5", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1665, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1704, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 32, in load_data\n  File \"/home/src/./src/data_ingestion/download_ticker_data.py\", line 64, in download_ticker_data\n    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)\n  File \"/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py\", line 894, in download_symbol\n    df = client.get_bars(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 735, in get_bars\n    bars = list(self.get_bars_iter(symbol,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 718, in get_bars_iter\n    for bar in bars:\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 594, in _data_get\n    resp = self.data_get(path, data=data, feed=feed,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 274, in data_get\n    return self._request(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 222, in _request\n    return self._one_request(method, url, opts, retry)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 248, in _one_request\n    raise_api_error(resp, http_error)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 83, in raise_api_error\n    raise APIError(error, http_error) from None\nalpaca_trade_api.rest.APIError: too many requests.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1552, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 182, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["too many requests."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1665, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1704, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 32, in load_data
  File "/home/src/./src/data_ingestion/download_ticker_data.py", line 64, in download_ticker_data
    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)
  File "/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py", line 894, in download_symbol
    df = client.get_bars(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 735, in get_bars
    bars = list(self.get_bars_iter(symbol,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 718, in get_bars_iter
    for bar in bars:
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 594, in _data_get
    resp = self.data_get(path, data=data, feed=feed,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 274, in data_get
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 222, in _request
    return self._one_request(method, url, opts, retry)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 248, in _one_request
    raise_api_error(resp, http_error)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 83, in raise_api_error
    raise APIError(error, http_error) from None
alpaca_trade_api.rest.APIError: too many requests.
2024-04-14T23:38:33 {"cpu": 1.12255859375, "cpu_total": 4, "cpu_usage": 0.2806396484375, "memory": 5245.0, "memory_total": 8874.0, "memory_usage": 0.5910525129592067, "pipeline_run_id": 110, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 110 in schedule 1 is alive.", "timestamp": 1713137913.567013, "uuid": "afd38fe11b254823af9da6a73ed7f41d"}
