2024-04-14T23:36:31 {"cpu": 0.81884765625, "cpu_total": 4, "cpu_usage": 0.2047119140625, "memory": 5465.0, "memory_total": 8874.0, "memory_usage": 0.6158440387649312, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137791.557657, "uuid": "37e0028d85584134bc549b9dd996498a"}
2024-04-14T23:36:52 {"cpu": 0.9736328125, "cpu_total": 4, "cpu_usage": 0.243408203125, "memory": 5041.0, "memory_total": 8874.0, "memory_usage": 0.5680640072120803, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137812.217662, "uuid": "c308d23b4ce6456eaa03d6fd4dd4ec7b"}
2024-04-14T23:37:05 {"cpu": 0.99072265625, "cpu_total": 4, "cpu_usage": 0.2476806640625, "memory": 5567.0, "memory_total": 8874.0, "memory_usage": 0.6273382916384945, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137825.899036, "uuid": "2de149a8f5d64cf2810671e9ba07d195"}
2024-04-14T23:37:17 {"cpu": 1.017578125, "cpu_total": 4, "cpu_usage": 0.25439453125, "memory": 5300.0, "memory_total": 8874.0, "memory_usage": 0.5972503944106378, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137837.72125, "uuid": "63c9426583b24961bea0a3100b680d70"}
2024-04-14T23:37:28 {"cpu": 1.0498046875, "cpu_total": 4, "cpu_usage": 0.262451171875, "memory": 5074.0, "memory_total": 8874.0, "memory_usage": 0.571782736082939, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137848.963914, "uuid": "c428722a5dd04777bbb718118b30db04"}
2024-04-14T23:37:40 {"cpu": 1.08740234375, "cpu_total": 4, "cpu_usage": 0.2718505859375, "memory": 5488.0, "memory_total": 8874.0, "memory_usage": 0.6184358800991661, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137860.034232, "uuid": "1238ab02d4e84425a5708c65ac87c7c0"}
2024-04-14T23:37:48 {"cpu": 1.09765625, "cpu_total": 4, "cpu_usage": 0.2744140625, "memory": 5137.0, "memory_total": 8874.0, "memory_usage": 0.5788821275636692, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137868.594283, "uuid": "56754ba64e49464aae6a6661d30e5e18"}
2024-04-14T23:37:57 {"cpu": 1.1123046875, "cpu_total": 4, "cpu_usage": 0.278076171875, "memory": 5422.0, "memory_total": 8874.0, "memory_usage": 0.6109984223574487, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137877.322075, "uuid": "9df79a47727e4b218a1090a6c91610c2"}
2024-04-14T23:38:03 {"block_run_id": 228, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Execute PipelineRun 114, BlockRun 228: pipeline fantastic_spellcaster block dwn_ticker_price", "timestamp": 1713137883.548097, "uuid": "59d372d4a3fb4df8a80d55a498b48c28"}
2024-04-14T23:38:05 {"cpu": 1.10595703125, "cpu_total": 4, "cpu_usage": 0.2764892578125, "memory": 5501.0, "memory_total": 8874.0, "memory_usage": 0.6199008338967771, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137885.335787, "uuid": "9da8fbaa41f54899b4f8e37b75b36897"}
2024-04-14T23:38:15 {"cpu": 1.10986328125, "cpu_total": 4, "cpu_usage": 0.2774658203125, "memory": 5271.0, "memory_total": 8874.0, "memory_usage": 0.5939824205544286, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137895.693233, "uuid": "ff40c2c08f574541a1bc790dd9a9b2e4"}
2024-04-14T23:38:21 {"block_run_id": 228, "block_uuid": "dwn_ticker_price", "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "EXCEPTION", "message": "BlockRun 228 (block_uuid: dwn_ticker_price) failed.", "timestamp": 1713137901.763886, "uuid": "b12913bacfd942ee96588a4bf87fa6e0", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1665, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1704, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 32, in load_data\n  File \"/home/src/./src/data_ingestion/download_ticker_data.py\", line 64, in download_ticker_data\n    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)\n  File \"/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py\", line 894, in download_symbol\n    df = client.get_bars(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 735, in get_bars\n    bars = list(self.get_bars_iter(symbol,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 718, in get_bars_iter\n    for bar in bars:\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 594, in _data_get\n    resp = self.data_get(path, data=data, feed=feed,\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 274, in data_get\n    return self._request(\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 222, in _request\n    return self._one_request(method, url, opts, retry)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 248, in _one_request\n    raise_api_error(resp, http_error)\n  File \"/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py\", line 83, in raise_api_error\n    raise APIError(error, http_error) from None\nalpaca_trade_api.rest.APIError: too many requests.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1552, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 182, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["too many requests."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1665, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1704, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 32, in load_data
  File "/home/src/./src/data_ingestion/download_ticker_data.py", line 64, in download_ticker_data
    response_dict[symbol] = vbt.AlpacaData.download_symbol(symbol, start=start_date, end=end_date)
  File "/usr/local/lib/python3.10/site-packages/vectorbt/data/custom.py", line 894, in download_symbol
    df = client.get_bars(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 735, in get_bars
    bars = list(self.get_bars_iter(symbol,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 718, in get_bars_iter
    for bar in bars:
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 594, in _data_get
    resp = self.data_get(path, data=data, feed=feed,
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 274, in data_get
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 222, in _request
    return self._one_request(method, url, opts, retry)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 248, in _one_request
    raise_api_error(resp, http_error)
  File "/usr/local/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 83, in raise_api_error
    raise APIError(error, http_error) from None
alpaca_trade_api.rest.APIError: too many requests.
2024-04-14T23:38:23 {"cpu": 1.12451171875, "cpu_total": 4, "cpu_usage": 0.2811279296875, "memory": 5566.0, "memory_total": 8874.0, "memory_usage": 0.6272256028848321, "pipeline_run_id": 114, "pipeline_schedule_id": 1, "pipeline_uuid": "fantastic_spellcaster", "hostname": "65ebb88fe12a", "level": "INFO", "message": "Pipeline fantastic_spellcaster for run 114 in schedule 1 is alive.", "timestamp": 1713137903.964769, "uuid": "0c433cce63dd49bb884fe40b02985676"}
